services:
  web:
    build: .
    ports:
      - 8000:3000
    networks:
      - mysql
  database:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: plance
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - --sql_mode=
    networks:
      - mysql

volumes:
  db-data:

networks:
  mysql: